name: Run Clang Static Analysis
on:
  push:
  pull_request:
#  schedule:
#    - cron: '3 20 * * SUN'

jobs:
  clang-analyzer:
    name: Clang static analysis
    runs-on: ubuntu-20.04
    env:
      SANITIZERS:
      UNIT_TESTS: no
      CLANG_STATIC_ANALYZER: yes
    defaults:
      run:
        working-directory: ./pdns/dnsdistdist/
    steps:
      - uses: PowerDNS/pdns/set-ubuntu-mirror@meta
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 5
          submodules: recursive
      - name: get timestamp for cache
        id: get-stamp
        run: |
          echo "stamp=$(/bin/date +%s)" >> "$GITHUB_OUTPUT"
        shell: bash
      - name: let GitHub cache our ccache data
        uses: actions/cache@v3.2.5
        with:
          path: ~/.ccache
          key: dnsdist-full-clang-static-analyzer-ccache-${{ steps.get-stamp.outputs.stamp }}
          restore-keys: dnsdist-full-clang-static-analyzer-ccache-
      - run: ../../build-scripts/gh-actions-setup-inv  # this runs apt update+upgrade
      - run: inv apt-fresh
      - run: inv install-clang
      - run: sudo apt install clang-tools-12
      - run: inv install-dnsdist-build-deps
      - run: inv ci-autoconf
      - run: inv ci-dnsdist-configure full
      - run: inv ci-dnsdist-make
      - run: ccache -s
